apiVersion: v1
kind: Namespace
metadata:
  name: webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  namespace: webserver
  labels:
    app: go-server
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: ffdzzr/go-simple-server:v2.0.0
        ports:
          - name: go-server-port
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /liveness
            port: go-server-port
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: go-server-port
          failureThreshold: 1
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /readiness
            port: go-server-port
          failureThreshold: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: webserver
spec:
  type: NodePort
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010 